//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/InfoSupport.Trainingen")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/InfoSupport.Trainingen", IsNullable=false)]
public partial class Course {
    
    private string codeField;
    
    private string nameField;
    
    private string supplierCodeField;
    
    private string supplierNameField;
    
    private string activeField;
    
    private long courseIdField;
    
    private CourseCourseImplementation[] courseImplementationsField;
    
    private System.DateTime dateCreatedField;
    
    private string descriptionField;
    
    private string durationField;
    
    private string followUpCoursesField;
    
    private string materialField;
    
    private string prerequisiteCoursesField;
    
    private string prerequisitesField;
    
    private decimal priceField;
    
    private CourseCourseSummary[] relatedCoursesField;
    
    private string shortDescriptionField;
    
    private string statusField;
    
    private string subjectsField;
    
    private string typeField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SupplierCode {
        get {
            return this.supplierCodeField;
        }
        set {
            this.supplierCodeField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierName {
        get {
            return this.supplierNameField;
        }
        set {
            this.supplierNameField = value;
        }
    }
    
    /// <remarks/>
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    public long CourseId {
        get {
            return this.courseIdField;
        }
        set {
            this.courseIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CourseImplementation", IsNullable=false)]
    public CourseCourseImplementation[] CourseImplementations {
        get {
            return this.courseImplementationsField;
        }
        set {
            this.courseImplementationsField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FollowUpCourses {
        get {
            return this.followUpCoursesField;
        }
        set {
            this.followUpCoursesField = value;
        }
    }
    
    /// <remarks/>
    public string Material {
        get {
            return this.materialField;
        }
        set {
            this.materialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrerequisiteCourses {
        get {
            return this.prerequisiteCoursesField;
        }
        set {
            this.prerequisiteCoursesField = value;
        }
    }
    
    /// <remarks/>
    public string Prerequisites {
        get {
            return this.prerequisitesField;
        }
        set {
            this.prerequisitesField = value;
        }
    }
    
    /// <remarks/>
    public decimal Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CourseSummary", IsNullable=false)]
    public CourseCourseSummary[] RelatedCourses {
        get {
            return this.relatedCoursesField;
        }
        set {
            this.relatedCoursesField = value;
        }
    }
    
    /// <remarks/>
    public string ShortDescription {
        get {
            return this.shortDescriptionField;
        }
        set {
            this.shortDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string Subjects {
        get {
            return this.subjectsField;
        }
        set {
            this.subjectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/InfoSupport.Trainingen")]
public partial class CourseCourseImplementation {
    
    private System.DateTime[] daysField;
    
    private long idField;
    
    private string languageField;
    
    private string locationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DateTime", IsNullable=false)]
    public System.DateTime[] Days {
        get {
            return this.daysField;
        }
        set {
            this.daysField = value;
        }
    }
    
    /// <remarks/>
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/InfoSupport.Trainingen")]
public partial class CourseCourseSummary {
    
    private string codeField;
    
    private string nameField;
    
    private string supplierCodeField;
    
    private string supplierNameField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SupplierCode {
        get {
            return this.supplierCodeField;
        }
        set {
            this.supplierCodeField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierName {
        get {
            return this.supplierNameField;
        }
        set {
            this.supplierNameField = value;
        }
    }
}
